USE [master]
GO

/****** Object:  Database [LibararyDB]    Script Date: 9/28/2020 8:11:07 PM ******/
CREATE DATABASE [LibararyDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LibararyDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\LibararyDB.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LibararyDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\LibararyDB.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LibararyDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LibararyDB] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [LibararyDB] SET ANSI_NULLS ON 
GO

ALTER DATABASE [LibararyDB] SET ANSI_PADDING ON 
GO

ALTER DATABASE [LibararyDB] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [LibararyDB] SET ARITHABORT ON 
GO

ALTER DATABASE [LibararyDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LibararyDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LibararyDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LibararyDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LibararyDB] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [LibararyDB] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [LibararyDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LibararyDB] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [LibararyDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LibararyDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LibararyDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LibararyDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LibararyDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LibararyDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LibararyDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LibararyDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LibararyDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LibararyDB] SET RECOVERY FULL 
GO

ALTER DATABASE [LibararyDB] SET  MULTI_USER 
GO

ALTER DATABASE [LibararyDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LibararyDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LibararyDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LibararyDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LibararyDB] SET  READ_WRITE 
GO


